/* SVARA style reminder: treatment menu as editorial index, eucalyptus field, terracotta highlights, no generic service-card grid. */

import { ArrowUpRight, Plus } from "lucide-react";
const items = [
  { n: "01", title: "The Unwind", desc: "Full-body bodywork for wired minds and tired muscles. Slow compressions, warm oil, and space to exhale.", time: "75 min", price: "IDR 950K" },
  { n: "02", title: "Skin / Soil", desc: "A botanical facial ritual that works with your skin barrier, not against it. Gentle exfoliation, sculptural massage, mineral mask.", time: "60 min", price: "IDR 820K" },
  { n: "03", title: "Breath Room", desc: "A guided session for when your breath feels shallow and your thoughts too loud. No experience required.", time: "45 min", price: "IDR 650K" },
  { n: "04", title: "The Long Return", desc: "A considered combination of bodywork and facial care for a deeper reset. Includes tea and a take-home practice.", time: "120 min", price: "IDR 1.450K" },
];
export default function Treatments() {
  return <div className="pt-20">
    <section className="px-6 py-24 lg:px-12 lg:py-32"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.62fr_1fr]"><div className="lg:sticky lg:top-28 lg:h-fit"><p className="chapter mb-6 text-[#c97861]">01 / Treatments</p><h1 className="max-w-3xl font-display text-6xl leading-[.86] lg:text-8xl">Begin where<br/><em>you are.</em></h1><p className="mt-10 max-w-md text-sm leading-7 text-[#4a5d60]">Every session starts with a conversation, not a clipboard. Tell us what feels present; we’ll help shape the rest.</p></div><div className="image-wrap ml-auto aspect-[3/4] w-full max-w-sm lg:mt-10"><img src="https://raw.content-delivery.centrova.id/Centrova-ID/svara-wellness/main/github-assets/svara/ritual.webp" alt="Botanical ritual vessel in warm morning light" className="h-full w-full object-cover"/><p className="mt-3 text-[10px] uppercase tracking-[.16em] text-[#4a5d60]">A slower kind of precision / 08:12</p></div></div></section>
    <section className="bg-[#e5eee7] px-6 py-20 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1440px] border-t border-[#123c43]/25">{items.map(x => <div key={x.n} className="grid gap-6 border-b border-[#123c43]/25 py-8 lg:grid-cols-[80px_1fr_1.3fr_150px_160px] lg:items-start"><span className="font-display text-3xl text-[#c97861]">{x.n}</span><h2 className="font-display text-4xl lg:text-5xl">{x.title}</h2><p className="max-w-sm text-sm leading-6 text-[#4a5d60]">{x.desc}</p><p className="text-[10px] font-bold uppercase tracking-[.16em]">{x.time}<br/><span className="mt-2 inline-block font-normal text-[#4a5d60]">{x.price}</span></p><a href="/contact" className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em]">Choose this <ArrowUpRight size={15}/></a></div>)}</div><div className="mt-16 flex items-center gap-3 text-sm text-[#4a5d60]"><Plus size={16} className="text-[#c97861]"/> Ask about prenatal care, restorative packages, or practitioner recommendations when you book.</div></section>
  </div>;
}
